#!/bin/bash
#PBS -q standard
#PBS -l nodes=1
#PBS -l walltime=12:00:00
#PBS -o spherocyl_strain.log
#PBS -N sp_str_p50n512dg1e-4
#PBS -j oe

cd $PBS_O_WORKDIR
echo Running on host `hostname`
echo Time is `date`
echo PBS_NODEFILE is $PBS_NODEFILE

~/spherocyls/exe/cpp_spherocyl_strain /scratch/tmarscha/data/spherocyl/test/sd0000000000.dat /scratch/tmarscha/data/spherocyl/test2/ 512 1e-4 0.025 5.0 0.01 0.00001 0.1 0.5 2.0 0.5 > ~/spherocyls/sp_str_p50n512dg1e-4.out