#!/bin/sh
#PBS -q blugpu
#PBS -l nodes=1:gpus=1
#PBS -l walltime=48:00:00
#PBS -o spherocyl.log
#PBS -N spherocyl
#PBS -j oe
#
cd $PBS_O_WORKDIR
echo Running on host `hostname`
echo Time is `date`
echo PBS_NODEFILE is $PBS_NODEFILE

export COMPUTE_PROFILE=1
export COMPUTE_PROFILE_LOG=~/sph_cyl/output/cuda_profile.log
export COMPUTE_PROFILE_CONFIG=~/sph_cyl/exe/.cuda_profile_config

~/sph_cyl/exe/spherocyl > ~/sph_cyl/output/spherocyl.out